name: Build, Test and Push Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      push_to_registry:
        description: 'Push to Quay.io after tests'
        required: true
        type: boolean
        default: false
      run_rag_tests:
        description: 'Run RAG integration tests'
        required: true
        type: boolean
        default: true
      image_tag:
        description: 'Custom image tag (optional)'
        required: false
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies and link package
        run: |
          # First try to use the lock file
          npm ci || {
            echo "::warning::npm ci failed, falling back to npm install to update lock file"
            # If npm ci fails, update the lock file and try again
            npm install
            # Now that the lock file is updated, try npm ci again
            npm ci
          }
          npm link
          # Verify kanbn is available
          which kanbn || echo "kanbn not found in PATH"
          echo "Node modules bin directory: $(npm bin -g)"
          # Add global npm bin to PATH
          echo "$(npm bin -g)" >> $GITHUB_PATH

      - name: Build container for testing
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: kanbn:test
          build-args: |
            NPM_CONFIG_PREFIX=/usr/local

      - name: Setup and verify Ollama
        run: |
          # Install Ollama
          curl https://ollama.ai/install.sh | sh

          # Start Ollama service
          ollama serve &
          echo "Started Ollama service in background"

          # Wait for Ollama to be ready (up to 30 seconds)
          MAX_RETRIES=30
          RETRY_COUNT=0
          until curl -s http://localhost:11434/api/tags > /dev/null; do
            if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
              echo "Error: Ollama failed to start after $MAX_RETRIES seconds"
              exit 1
            fi
            echo "Waiting for Ollama to be ready... ($(( MAX_RETRIES - RETRY_COUNT )) seconds remaining)"
            sleep 1
            RETRY_COUNT=$((RETRY_COUNT + 1))
          done
          echo "✓ Ollama service is running"

          # Pull the model
          ollama pull qwen3
          echo "✓ Model pulled successfully"

          # Verify model is available
          if ! ollama list | grep -q "qwen3"; then
            echo "Error: qwen3 model not found after pulling"
            exit 1
          fi
          echo "✓ Model verified"

      - name: Test Container Functionality
        run: |
          # Create test directory
          TEST_DIR=$(mktemp -d)
          echo "Created test directory: $TEST_DIR"

          # Test basic kanbn functionality
          echo "Testing basic kanbn functionality..."
          docker run --rm -v $TEST_DIR:/workspace -w /workspace \
            -e KANBN_ENV=test \
            -e NODE_ENV=test \
            kanbn:test /bin/bash -c '
              # Test basic commands
              set -e
              kanbn init --name "TestProject" --description "Testing kanbn in container" && \
              kanbn add "test-task" --name "Test Task" --description "Testing task creation" && \
              kanbn board && \
              kanbn status
            ' || { echo "::warning::Basic kanbn functionality test failed"; }

          # Run RAG tests if requested or if this is a release
          if [ "${{ github.event_name == 'release' || github.event.inputs.run_rag_tests == 'true' }}" = "true" ]; then
            echo "Running RAG integration tests..."

            # Test container bootstrap script with different project modes
            echo "Testing container bootstrap script with default mode (3)..."
            docker run --rm -v $TEST_DIR/mode3:/workspace -w /workspace \
              -e KANBN_ENV=test \
              -e NODE_ENV=test \
              -e PROJECT_MODE=3 \
              -e PROJECT_NAME="Container Test Mode 3" \
              -e PROJECT_DESCRIPTION="Testing kanbn in container environment with mode 3" \
              -e USE_OLLAMA=true \
              -e OLLAMA_HOST=http://host.docker.internal:11434 \
              -e OLLAMA_MODEL=qwen3 \
              --network host \
              kanbn:test /bin/bash -c "chmod +x /app/examples/bootstrap_container.sh && /app/examples/bootstrap_container.sh" \
              || { echo "::warning::Container bootstrap script test with mode 3 failed but continuing..."; }

            # Instead of duplicating the repository cloning logic, use the dedicated test script
            echo "Testing SNO Quickstarts integration using dedicated test script..."
            docker run --rm -v $TEST_DIR/mode1:/workspace -w /workspace \
              -e KANBN_ENV=test \
              -e NODE_ENV=test \
              -e USE_OLLAMA=true \
              -e OLLAMA_HOST=http://host.docker.internal:11434 \
              -e OLLAMA_MODEL=qwen3 \
              --network host \
              kanbn:test /bin/bash -c "chmod +x /app/examples/test_sno_quickstarts_integration.sh && /app/examples/test_sno_quickstarts_integration.sh" \
              || { echo "::warning::SNO Quickstarts integration test failed but continuing..."; }

            echo "Testing container bootstrap script with mode 2 (existing repository)..."
            # First create a test repository
            mkdir -p $TEST_DIR/mode2/existing-repo
            cd $TEST_DIR/mode2/existing-repo
            git init
            echo "# Test Repository" > README.md
            git add README.md
            git config --global user.email "test@example.com"
            git config --global user.name "Test User"
            git commit -m "Initial commit"
            cd -

            docker run --rm -v $TEST_DIR/mode2:/workspace -w /workspace \
              -e KANBN_ENV=test \
              -e NODE_ENV=test \
              -e PROJECT_MODE=2 \
              -e REPO_PATH=/workspace/existing-repo \
              -e PROJECT_NAME="Container Test Mode 2" \
              -e PROJECT_DESCRIPTION="Testing kanbn in container environment with mode 2" \
              -e USE_OLLAMA=true \
              -e OLLAMA_HOST=http://host.docker.internal:11434 \
              -e OLLAMA_MODEL=qwen3 \
              -e GIT_COMMIT=true \
              --network host \
              kanbn:test /bin/bash -c "chmod +x /app/examples/bootstrap_container.sh && /app/examples/bootstrap_container.sh" \
              || { echo "::warning::Container bootstrap script test with mode 2 failed but continuing..."; }

            # Test RAG integrations using the CI/CD Makefile targets
            echo "Testing RAG integrations using CI/CD Makefile targets..."
            # First, copy the Makefile to the test directory
            cp $(pwd)/Makefile $TEST_DIR/
            cd $TEST_DIR

            # Option 1: Run all CI tests at once (includes mock, Ollama, and OpenRouter if available)
            echo "Running all CI tests..."
            docker run --rm -v $TEST_DIR:/app -w /app \
              -e KANBN_ENV=development \
              -e NODE_ENV=development \
              -e USE_OLLAMA=true \
              -e OLLAMA_HOST=http://host.docker.internal:11434 \
              -e OLLAMA_MODEL=qwen3 \
              -e OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY || '' }} \
              --network host \
              kanbn:test make ci-test-all \
              || { echo "::warning::Some CI tests failed but continuing..."; }

            # Option 2: Run individual CI tests (uncomment if needed for debugging)
            # echo "Running CI tests in mock mode..."
            # docker run --rm -v $TEST_DIR:/app -w /app \
            #   -e KANBN_ENV=test \
            #   -e NODE_ENV=test \
            #   --network host \
            #   kanbn:test make ci-test-mock \
            #   || { echo "::warning::CI mock tests failed but continuing..."; }
            #
            # echo "Running CI tests with Ollama..."
            # docker run --rm -v $TEST_DIR:/app -w /app \
            #   -e KANBN_ENV=development \
            #   -e NODE_ENV=development \
            #   -e USE_OLLAMA=true \
            #   -e OLLAMA_HOST=http://host.docker.internal:11434 \
            #   -e OLLAMA_MODEL=qwen3 \
            #   --network host \
            #   kanbn:test make ci-test-ollama \
            #   || { echo "::warning::CI Ollama tests failed but continuing..."; }

            # Return to the original directory
            cd $(pwd)



            # Additional repository context integration tests
            echo "Testing repository context integration with Ollama..."
            docker run --rm -v $TEST_DIR:/workspace -w /workspace \
              -e KANBN_ENV=test \
              -e NODE_ENV=test \
              -e KANBN_ROOT=/app \
              -v $(pwd):/app \
              -e USE_OLLAMA=true \
              -e OLLAMA_HOST=http://host.docker.internal:11434 \
              -e OLLAMA_MODEL=qwen3 \
              --network host \
              kanbn:test /bin/bash -c "$(cat ./examples/test_repository_context_integration.sh)" \
              || { echo "::warning::Repository context integration test with Ollama failed but continuing..."; }
          fi

          echo "All container tests completed"

      - name: Login to Quay.io
        if: success() && (github.event_name == 'release' || github.event.inputs.push_to_registry == 'true')
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'release' || github.event.inputs.push_to_registry == 'true' }}
          tags: |
            ${{ github.event_name == 'release' || github.event.inputs.push_to_registry == 'true' && 'quay.io/takinosh/kanbn:latest' || '' }}
            ${{ github.event_name == 'release' && format('quay.io/takinosh/kanbn:{0}', github.event.release.tag_name) || github.event.inputs.image_tag != '' && format('quay.io/takinosh/kanbn:{0}', github.event.inputs.image_tag) || '' }}
