name: Issue Reporter

on:
  workflow_run:
    workflows: ["Tests", "Publish to npm"]
    types: [completed]

jobs:
  report-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
      - name: Get workflow run info
        uses: actions/github-script@v7
        id: workflow-info
        with:
          script: |
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            const failedJobs = jobs.data.jobs.filter(job => job.conclusion === 'failure');
            return {
              workflow_name: run.data.name,
              failed_jobs: failedJobs.map(job => ({
                name: job.name,
                html_url: job.html_url,
                steps: job.steps.filter(step => step.conclusion === 'failure').map(step => step.name)
              }))
            };

      - name: Create issue
        uses: actions/github-script@v7
        with:
          script: |
            const info = ${{ steps.workflow-info.outputs.result }};
            const issueBody = `
            # Workflow Failure Report
            
            The workflow **${info.workflow_name}** has failed.
            
            ## Failed Jobs:
            ${info.failed_jobs.map(job => `
            ### ${job.name}
            - Job URL: ${job.html_url}
            - Failed Steps:
              ${job.steps.map(step => `- ${step}`).join('\n              ')}
            `).join('\n')}
            
            ## Quick Links
            - [View Workflow Run](${context.payload.workflow_run.html_url})
            - [Repository](https://github.com/${context.repo.owner}/${context.repo.repo})
            - [Create Bug Report](https://github.com/${context.repo.owner}/${context.repo.repo}/issues/new?template=bug_report.md)
            
            ## How to Help
            1. Check the failed job logs using the links above
            2. If you can fix the issue, please submit a pull request
            3. If you need help, use the bug report template to provide more details
            
            @${context.repo.owner} - Please review this failure.
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🔴 Workflow Failure: ${info.workflow_name}`,
              body: issueBody,
              labels: ['bug', 'workflow-failure', 'needs-triage']
            });
