name: RAG Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of RAG test to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - ollama
        - openrouter
      debug_mode:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup and verify Ollama
        run: |
          # Install Ollama
          curl https://ollama.ai/install.sh | sh
          
          # Start Ollama service
          ollama serve &
          echo "Started Ollama service in background"
          
          # Wait for Ollama to be ready (up to 30 seconds)
          MAX_RETRIES=30
          RETRY_COUNT=0
          until curl -s http://localhost:11434/api/tags > /dev/null; do
            if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
              echo "Error: Ollama failed to start after $MAX_RETRIES seconds"
              exit 1
            fi
            echo "Waiting for Ollama to be ready... ($(( MAX_RETRIES - RETRY_COUNT )) seconds remaining)"
            sleep 1
            RETRY_COUNT=$((RETRY_COUNT + 1))
          done
          echo "✓ Ollama service is running"
          
          # Pull the model
          ollama pull llama2
          echo "✓ Model pulled successfully"
          
          # Verify model is available
          if ! ollama list | grep -q "llama2"; then
            echo "Error: llama2 model not found after pulling"
            exit 1
          fi
          echo "✓ Model verified"
          
      - name: Run Ollama RAG Tests
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'ollama'
        env:
          KANBN_ENV: test
          DEBUG: ${{ github.event.inputs.debug_mode == 'true' || 'true' }}
          KANBN_TEST_MODE: true
          OLLAMA_HOST: http://localhost:11434
          OLLAMA_MODEL: llama2
          USE_OLLAMA: true
        run: bash ./examples/test_ollama_rag_integrations\ copy.sh
        
      - name: Run OpenRouter RAG Tests
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'openrouter'
        env:
          KANBN_ENV: test
          DEBUG: ${{ github.event.inputs.debug_mode == 'true' || 'false' }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          USE_OLLAMA: false
        run: bash ./examples/test_openrouter_rag_integrations.sh
