name: RAG Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of RAG test to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - ollama
        - openrouter
      debug_mode:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Ollama
        run: |
          curl https://ollama.ai/install.sh | sh
          ollama pull llama2
          
      - name: Run Ollama RAG Tests
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'ollama'
        env:
          KANBN_ENV: test
          DEBUG: ${{ github.event.inputs.debug_mode == 'true' || 'true' }}
          KANBN_TEST_MODE: true
          OLLAMA_HOST: http://localhost:11434
          OLLAMA_MODEL: llama2
          USE_OLLAMA: true
        run: bash ./examples/test_ollama_rag_integrations\ copy.sh
        
      - name: Run OpenRouter RAG Tests
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'openrouter'
        env:
          KANBN_ENV: test
          DEBUG: ${{ github.event.inputs.debug_mode == 'true' || 'false' }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          USE_OLLAMA: false
        run: bash ./examples/test_openrouter_rag_integrations.sh
