name: Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Update package-lock.json
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          set -e
          npm test
        env:
          KANBN_ENV: test

      - name: Build package
        run: |
          set -e
          npm pack

      - name: Run binary tests
        run: |
          set -e
          chmod +x ./test-all-commands.sh
          ./test-all-commands.sh --use-built-package

      - name: Run AI initialization tests
        run: |
          set -e
          chmod +x ./test-ai-init.sh
          ./test-ai-init.sh
        env:
          KANBN_ENV: test

      - name: Run binary tests
        run: |
          set -e
          chmod +x ./test-ai-init-scenarios.sh
          ./test-ai-init-scenarios.sh

      - name: Run linting
        run: |
          set -e
          if [ -f package.json ]; then
            if npm ls eslint > /dev/null 2>&1; then
              npm run lint
            fi
          fi

      - name: Check documentation
        run: |
          set -e
          if [ -d docs ]; then
            if [ ! -f docs/index.html ]; then
              echo "Error: docs/index.html is missing"
              exit 1
            fi
            if [ ! -f docs/_sidebar.md ]; then
              echo "Error: docs/_sidebar.md is missing"
              exit 1
            fi
          fi
