name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          KANBN_ENV: test

      - name: Run linting
        run: |
          if [ -f package.json ]; then
            if npm ls eslint > /dev/null 2>&1; then
              npm run lint
            fi
          fi
        continue-on-error: true

      - name: Check documentation
        run: |
          if [ -d docs ]; then
            if [ ! -f docs/index.html ]; then
              echo "Error: docs/index.html is missing"
              exit 1
            fi
            if [ ! -f docs/_sidebar.md ]; then
              echo "Error: docs/_sidebar.md is missing"
              exit 1
            fi
          fi
