name: Tests

on:
  pull_request:
    branches: [ '*' ]  # Run on pull requests to any branch
  push:
    branches: [ '*' ]  # Run on pushes to any branch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Run linting
        run: |
          set -e
          if [ -f package.json ]; then
            if npm ls eslint > /dev/null 2>&1; then
              npm run lint
            fi
          fi

      - name: Install dependencies
        run: npm ci

      - name: Run Jest unit tests
        run: npm test
        env:
          CI: true
          DEBUG: true
          KANBN_ENV: test

      - name: Update package-lock.json
        run: npm install

      - name: Build package
        run: npm pack

      - name: Run binary tests
        run: |
          set -e
          chmod +x ./scripts/test-all-commands.sh
          ./scripts/test-all-commands.sh --use-built-package

      - name: Run AI initialization tests
        run: |
          set -e
          chmod +x ./scripts/test-ai-init.sh
          ./scripts/test-ai-init.sh
        env:
          KANBN_ENV: test
          DEBUG: true

      - name: Run AI scenario tests
        run: |
          set -e
          chmod +x ./scripts/test-ai-init-scenarios.sh
          ./scripts/test-ai-init-scenarios.sh
        env:
          KANBN_ENV: test
          DEBUG: true

      - name: Check documentation
        run: |
          set -e
          if [ -d docs ]; then
            if [ ! -f docs/index.html ]; then
              echo "Error: docs/index.html is missing"
              exit 1
            fi
            if [ ! -f docs/_sidebar.md ]; then
              echo "Error: docs/_sidebar.md is missing"
              exit 1
            fi
          fi
