name: Tests

# Temporarily disabled for development
# To re-enable, remove the following line and uncomment the 'on' section below
on: workflow_dispatch

# on:
#   pull_request:
#     branches: [ main, master ]
#   push:
#     branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Fix package-lock.json issues by using clean install
      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci || npm install

      # Run QUnit tests (legacy system)
      - name: Run QUnit tests
        run: |
          set -e
          npm test
        env:
          KANBN_ENV: test
          USE_REAL_API: false

      # Run MCP tests if available
      - name: Run MCP server tests
        run: |
          set -e
          if npm run test:mcp 2>/dev/null; then
            echo "MCP server tests passed"
          else
            echo "MCP server tests not available or failed"
            # Don't fail the build if MCP tests aren't available yet
            exit $([ "${{ matrix.node-version }}" == "22.x" ] && echo 1 || echo 0)
          fi
        env:
          KANBN_ENV: test
          MCP_TEST_MODE: true

      # Run MCP resource tests if available
      - name: Run MCP resource tests
        run: |
          set -e
          if npm run test:mcp:resources 2>/dev/null; then
            echo "MCP resource tests passed"
          else
            echo "MCP resource tests not available or failed"
            # Don't fail the build if MCP tests aren't available yet
            exit $([ "${{ matrix.node-version }}" == "22.x" ] && echo 1 || echo 0)
          fi
        env:
          KANBN_ENV: test
          MCP_TEST_MODE: true

      # Run MCP tools tests if available
      - name: Run MCP tools tests
        run: |
          set -e
          if npm run test:mcp:tools 2>/dev/null; then
            echo "MCP tools tests passed"
          else
            echo "MCP tools tests not available or failed"
            # Don't fail the build if MCP tests aren't available yet
            exit $([ "${{ matrix.node-version }}" == "22.x" ] && echo 1 || echo 0)
          fi
        env:
          KANBN_ENV: test
          MCP_TEST_MODE: true

      - name: Build package
        run: |
          set -e
          npm pack

      - name: Run binary tests
        run: |
          set -e
          chmod +x ./scripts/test-all-commands.sh
          ./scripts/test-all-commands.sh --use-built-package

      - name: Run AI initialization tests
        run: |
          set -e
          chmod +x ./scripts/test-ai-init.sh
          ./scripts/test-ai-init.sh
        env:
          KANBN_ENV: test
          USE_REAL_API: false

      - name: Run AI initialization scenarios
        run: |
          set -e
          chmod +x ./scripts/test-ai-init-scenarios.sh
          ./scripts/test-ai-init-scenarios.sh
        env:
          KANBN_ENV: test
          USE_REAL_API: false

      - name: Run linting
        run: |
          set -e
          if [ -f package.json ]; then
            if npm ls eslint > /dev/null 2>&1; then
              npm run lint
            fi
          fi

      - name: Check documentation
        run: |
          set -e
          if [ -d docs ]; then
            if [ ! -f docs/index.html ]; then
              echo "Error: docs/index.html is missing"
              exit 1
            fi
            if [ ! -f docs/_sidebar.md ]; then
              echo "Error: docs/_sidebar.md is missing"
              exit 1
            fi
          fi
